Algoritmo "exemplo vetor"


Var


A: vetor [0..9] de real

n ,i : inteiro



Inicio

  escreva("Quantos numeros você vai digitar? ")
  leia(n)

      para i de 0 ate n-1 faca
         escreva("Digite um numero: ")
         leia(A[i])

      fimpara
      
   escreval
   escreval("Numeros Digitados: ")

       para i de 0 ate n-1 faca
         escreval(A[i])
       fimpara


Fimalgoritmo