Algoritmo "Terreno"

Var

  largura , comprimento , valor , area , total : real

Inicio


  escreval("Digite a Largura do terreno: ")
  leia(largura)
  escreval("Digite o comprimento do terreno: ")
  leia(comprimento)
  escreval("Digite o valor do metro quadrado: ")
  leia(valor)
  area <- (largura * comprimento)
  total <- (area * valor)
  escreval ("O valor que o terreno está sendo: ",total:8:2," reais, com uma area de ",area," metros quadrados")





Fimalgoritmo